*** Variables ***
${FYEAREND}     //input[@id='react-project_impact-fy_end_date_0']
${OVERSEASSALES1}     //input[@id='react-project_impact-overseas_sales_0']
${OVERSEASSALES2}     //input[@id='react-project_impact-overseas_sales_1']
${OVERSEASSALES3}     //input[@id='react-project_impact-overseas_sales_2']
${OVERSEASSALES4}     //input[@id='react-project_impact-overseas_sales_3']

${OVERSEASINVESTMENTS1}     //input[@id='react-project_impact-overseas_investments_0']
${OVERSEASINVESTMENTS2}     //input[@id='react-project_impact-overseas_investments_1']
${OVERSEASINVESTMENTS3}     //input[@id='react-project_impact-overseas_investments_2']
${OVERSEASINVESTMENTS4}     //input[@id='react-project_impact-overseas_investments_3']


${PROJECTIONRATIONALE}     //textarea[@id='react-project_impact-rationale_remarks']
${NONTANGILEBENEFITS}     //textarea[@id='react-project_impact-benefits_remarks']

${SAVEBUTTON}    //button[@id='save-btn']
${NEXTBUTTON}    //button[@id='next-btn']
${PREVIOUSBUTTON}     //button[@id='back-btn']

