*** Variables ***

${THIRDPARTYVENDORS}    //div[@id='react-project_cost-vendors-accordion-header']
${THIRDPARTADDITEM}    //button[@id='react-project_cost-vendors-add-item']
${VENDORREGISTEREDSG}    //div[@class='controls bgp-radio-text-format']//label[1]
${VENDORREGISTEROVS}     //body//label[2]
${VENDORNAME}     //input[@id='react-project_cost-vendors-0-vendor_name']
${ESTIMATEDCOST}    /input[@id='react-project_cost-vendors-0-amount_in_billing_currency']



${OFFICERENTAL}     //div[@id='react-project_cost-office_rentals-accordion-header']
${SALARIES}     //div[@id='react-project_cost-salaries-accordion-header']

${REMARKS}     //textarea[@id='react-project_cost-remarks']

${COSTDETAILSNEXTBUTTON}    //button[@id='next-btn']



