*** Variables ***

${LoginWithCorpPass}     //div[@class='bgp-btn bgp-btn-loginCorpPass margin-top-sm margin-btm-md']
${NRICLOCATOR}     //input[@placeholder='NRIC']
${FULLNAMELOCATOR}    //input[@placeholder='Name']
${UENLOCATOR}     //input[@placeholder='UEN']
${ROLELOCATOR}    //select[@name='CPRole']
${LOGINBUTTONLOCATOR}    //form[2]//button[1]

${NRICVALUE}     public
${FULLNAMEVALUE}    Tan Ah Kow
${UENVALUE}    BGPQEDEMO
${ROLEVALUE}    Acceptor


